### ISSUE TITLE
Contact Möglichkeit

### ISSUE THREAD

**Issue by morriswinkler** [xHain-hackspace/xHain-hackspace.github.io#3]
Fehlt leider,

ansonsten ist denn Heute offen ?

Grüsse

**Comment by Samwise007** [comment]
Ja. Ab 17:00 Uhr.
LG Felix

On May 16, 2016 1:06:46 PM GMT+02:00, morriswinkler notifications@github.com wrote:

> Fehlt leider,
> 
> ansonsten ist denn Heute offen ?
> 
> Grüsse
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xHain-hackspace/xHain-hackspace.github.io/issues/3

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
